# Configuration du moteur de recherche arXiv
database:
  chroma_path: "./data/chroma_db"
  collection_name: "arxiv_papers"

ollama:
  base_url: "http://localhost:11434"
  embedding_model: "nomic-embed-text"
  generation_model: "gemma2:2b"

search:
  max_results: 50
  similarity_threshold: 0.7
  hybrid_weights:
    semantic: 0.7
    lexical: 0.3

data:
  arxiv_data_path: "./data/arxiv_papers.json"
  chunk_size: 1000
  chunk_overlap: 200

streamlit:
  title: "ArXiv Search Engine"
  page_icon: "🔍"
  layout: "wide"

visualization:
  max_network_nodes: 100
  trends_time_window: "1Y"# Configuration du projet
